version: '3.2'
services:
  canfar:
    hostname: ${HOSTNAME:-localhost}
    image: jekyll/jekyll:4
    command: bash -c "bundle install && jekyll serve 0.0.0.0"
    ports:
      - 4000:4000
    volumes:
      - './:/srv/jekyll'
    networks:
      - canfar

networks:
  canfar:
